### ISSUE TITLE
NIPS accept paper

### ISSUE THREAD

**Issue by richhh520** [jjbrophy47/machine_unlearning#26]
Dear jjbrophy,

Our paper Fast Model DeBias with Machine Unlearning has been accepted by NIPS'23. Here is the link:
https://openreview.net/forum?id=BL9Pc7xsdX&noteId=BL9Pc7xsdX

We will appreciate it if you could update this paper.

Thanks,
Ruizhe

**Comment by jjbrophy47** [comment]
Hi Ruizhe, congratulations on your paper acceptance. Please open a pull request (PR) to have your paper added to the list.

**Comment by jjbrophy47** [comment]
Okay, your paper venue has been updated to NeurIPS, thanks for reaching out @richhh520!
