### ISSUE TITLE
ICLR 2024 accepted unlearning papers

### ISSUE THREAD

**Issue by ljcc0930** [jjbrophy47/machine_unlearning#29]
- [SalUn: Empowering Machine Unlearning via Gradient-based Weight Saliency in Both Image Classification and Generation](https://openreview.net/forum?id=gn0mIhQGNM)
- [Machine Unlearning for Image-to-Image Generative Models](https://openreview.net/forum?id=9hjVoPWPnh)
- [Label-Agnostic Forgetting: A Supervision-Free Unlearning in Deep Models](https://openreview.net/forum?id=SIZWiya7FE)

**Comment by jjbrophy47** [comment]
Added, thanks @ljcc0930! Also, next time feel free to just open a pull request.
