### ISSUE TITLE
New paper on LLM Unlearning

### ISSUE THREAD

**Issue by yihuaihong** [jjbrophy47/machine_unlearning#42]
Hi, Dear manager,
I would like to know whether you would be willing to add our new paper: Intrinsic Evaluation of Unlearning Using Parametric Knowledge Traces.
We believe that the knowledge vectors we have identified, their verified importance in storing target knowledge, and the corresponding analysis have significant implications for LLM unlearning areas. 

Thank you very much for your kindness!

paper: https://arxiv.org/pdf/2406.11614
code: https://github.com/yihuaihong/ConceptVectors
website: https://yihuaihong.github.io/ConceptVectors.github.io

**Comment by jjbrophy47** [comment]
Added, thanks @yihuaihong!

**Comment by yihuaihong** [comment]
Thank you very much😀
