### ISSUE TITLE
New paper on Robustness of LLM Unlearning

### ISSUE THREAD

**Issue by J4Q8** [jjbrophy47/machine_unlearning#43]
Hi!

Would you be willing to add the paper [An Adversarial Perspective on Machine Unlearning for AI Safety](https://arxiv.org/abs/2409.18025) to your repository? We show that current unlearning methods are only obfuscating knowledge (just like standard safety training) instead of completely erasing it from the model weights.

Twitter thread: https://x.com/jakub_lucki/status/1839672063667167433
Code: https://github.com/ethz-spylab/unlearning-vs-safety

Thanks in advance!

Best regards,
Jakub

**Comment by jjbrophy47** [comment]
Hi Jakub,

I've added your paper, thanks for reaching out.

Best,
Jonathan Brophy
